name: build

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync

    - name: Build
      run: uv build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
